name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Get current repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: vshadbolt/stable-diffusion-telegram-bot:latest
    
      - name: Docker Hub Description (README.md)
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vshadbolt/stable-diffusion-telegram-bot
          readme-filepath: README.md
